HairSalonReal.Solution/HairSalon/Models/Client.cs
namespace HairSalon.Models
{
    public class Client
    {
        public int ClientId { get; set; }
        public string Name { get; set; }
        public string HairType { get; set; }
        public string ServiceNeeded { get; set;}
        public int StylistId { get; set; }
        public virtual Stylist Stylist { get; set; }
    }
}

HairSalonReal.Solution/HairSalon/Models/Clients.cs
namespace HairSalon.Models
{
    public class Client
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string HairType { get; set; }
        public int StylistId { get; set; }
        public virtual Stylist Stylist { get; set; }
    }
}

HairSalonReal.Solution/HairSalon/Models/HairSalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Models
{
    public class HairSalonContext : DbContext
    {
        public virtual DbSet<Stylist> Stylists { get; set; }
        public DbSet<Client> Clients { get; set; }

        public HairSalonContext(DbContextOptions options) : base(options) { }
    }
}

HairSalonReal.Solution/HairSalon/Models/LaurenMusanteContext.cs
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Models
{
    public class LaurenMusanteContext : DbContext
    {
        public virtual DbSet<Stylist> Stylists { get; set; }
        public DbSet<Client> Clients { get; set; }

        public LaurenMusanteContext(DbContextOptions options) : base(options) { }
    }
}

HairSalonReal.Solution/HairSalon/Models/Stylist.cs
using System.Collections.Generic;

namespace HairSalon.Models
{
    public class Stylist
    {
        public Stylist()
        {
            this.Clients = new HashSet<Client>(); 
        }

        public string Name { get; set; }
        public string Specialty { get; set; }
        public int StylistId { get; set; }
        public virtual ICollection<Client> Clients { get; set; } 
        
    }
}

HairSalonReal.Solution/HairSalon/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HairSalon.Controllers
{
    public class ClientsController : Controller
    {
        private readonly HairSalonContext _db;

        public ClientsController(HairSalonContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            List<Client> model = _db.Clients.Include(client => client.Stylist).ToList(); 
            return View(model);
        }

        public ActionResult Create()
        {
            ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Client client)
        {
            _db.Clients.Add(client);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
            return View(thisClient);
        }
    }
}

HairSalonReal.Solution/HairSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace HairSalon.Controllers
{
    public class HomeController : Controller
    {

        [HttpGet("/")]
        public ActionResult Index()
        {
            return View();
        }

    }
}

HairSalonReal.Solution/HairSalon/Controllers/StylistsController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace HairSalon.Controllers
{
    public class StylistsController : Controller
    {
        private readonly HairSalonContext _db;

        public StylistsController(HairSalonContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            List<Stylist> model = _db.Stylists.ToList();
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Stylist Stylist)
        {
            _db.Stylists.Add(Stylist);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
            return View(thisStylist);
        }

        public ActionResult Edit(int id)
        {
            var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
            return View(thisStylist);
        }

        [HttpPost]
        public ActionResult Edit(Stylist stylist)
        {
            _db.Entry(stylist).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        // public ActionResult Delete(int id)
        // {
        //     var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
        //     return View(thisStylist);
        // }

        // [HttpPost, ActionName("Delete")]
        // public ActionResult DeleteConfirmed(int id)
        // {
        //     var thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
        //     _db.Stylists.Remove(thisStylist);
        //     _db.SaveChanges();
        //     return RedirectToAction("Index");
        // }
    }
}

HairSalonReal.Solution/HairSalon/Views/Clients/Create.cshtml
@{
    Layout = "_Layout";
}
@model HairSalon.Models.Client
<h1>Add a new client</h1>
    @using (Html.BeginForm())
    {
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name)
        <br>
        @Html.LabelFor(model => model.HairType)
        @Html.TextBoxFor(model => model.HairType)
        <br>
        @Html.LabelFor(model => model.ServiceNeeded)
        @Html.TextBoxFor(model => model.ServiceNeeded)  
        <br>         
        @Html.LabelFor(model => model.Stylist)
        @Html.DropDownList("StylistId");
        <hr>
        <input type="submit" value="Add new client" class="btn btn-success" />
        <hr>
    }
    <h2>@Html.ActionLink("Show all clients", "Index")</h2>

HairSalonReal.Solution/HairSalon/Views/Clients/Details.cshtml
@{
    Layout = "_Layout";
} 
@model HairSalon.Models.Client
@using HairSalon.Models

 <h1> Client Details: </h1>
    <h3>Client Name: @Model.Name</h3>
    <h3>Hair Type: @Model.HairType</h3>
    <h3>Service Needed: @Model.ServiceNeeded</h3>

HairSalonReal.Solution/HairSalon/Views/Clients/Index.cshtml
@{
    Layout = "_Layout";
}
@using HairSalon.Models
@model List<HairSalon.Models.Client>

<h1> Your Current Clients: </h1>
<hr>
@if (@Model.Count == 0)
    {
    <h3>You have not added any clients yet.</h3>
    } 

    @foreach (Client client in Model)
    {
        <li>@Html.ActionLink($"{client.Name}", "Details", new { id = client.ClientId }) | @client.Stylist.Name  </li>
    }

<h2>@Html.ActionLink("Add new client", "Create")</h2>
<h2>@Html.ActionLink("Home", "Index", "Home")</h2>

HairSalonReal.Solution/HairSalon/Views/Home/Index.cshtml
@{
    Layout = "_Layout";
}
@using HairSalon.Models;
@model List<HairSalon.Models.Stylist>;

<h1>✂️ Hello Claire ✂️</h1> 


<h3><em>What would you like to do today?</em></h3>
<h2>@Html.ActionLink("See all stylists", "Index", "Stylists")</h2>
<h2>@Html.ActionLink("See all clients", "Index", "Clients")</h2>

HairSalonReal.Solution/HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>Clients</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link href="~/css/styles.css" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Lobster&display=swap" rel="stylesheet">
</head>
<body>
    <div class= "grad">
    <div class = "container">
        @RenderBody()
    </div>
    </div>
</body>

HairSalonReal.Solution/HairSalon/Views/Stylists/Create.cshtml
@{
    Layout = "_Layout";
}
@model HairSalon.Models.Stylist

<h1>Add a new stylist</h1>
    @using (Html.BeginForm())
    {
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name)
        <br>
        @Html.LabelFor(model => model.Specialty)
        @Html.TextBoxFor(model => model.Specialty)
        <br>

        <input type="submit" value="Add Stylist" class="btn btn-success" />
    }
    
<h2>@Html.ActionLink("Show all Stylists", "Index")</h2>

HairSalonReal.Solution/HairSalon/Views/Stylists/Details.cshtml
@{
    Layout = "_Layout";
}
@model HairSalon.Models.Stylist

        <h1>Stylist Details</h1>
        <hr />
        <h2>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h2>
        <h3>@Html.DisplayNameFor(model => model.Specialty): @Html.DisplayFor(model => model.Specialty)</h3>

        <h2>@Html.ActionLink("Home", "Index", "Home")</h2>

HairSalonReal.Solution/HairSalon/Views/Stylists/Index.cshtml
@{
    Layout = "_Layout";
}
@using HairSalon.Models;
@model List<HairSalon.Models.Stylist>;

<h1>Your Current Stylists</h1>
<hr>

@if (@Model.Count == 0)
{
  <h3>You have not added any stylists yet.</h3>
} 

@foreach (Stylist stylist in Model)
{
  <li>@Html.ActionLink($"{stylist.Name}", "Details", new { id = stylist.StylistId })</li>
}

<h2>@Html.ActionLink("Add new stylist", "Create")</h2>

<h2>@Html.ActionLink("Home", "Index", "Home")</h3>